### ISSUE TITLE
Need half-step option to support some encoders for GUI use

### ISSUE THREAD

**Issue by urbite** [TTitanUA/micropython_rotary_encoder#3]
The KY-040 is a popular and low-cost rotary encoder which has a mechanical detent. Between each detent step there are only 2 transitions of the CLK and DT signals, not a full cycle (4 transitions). The existing library only signals a rotation increment or decrement after 4 transitions have been detected.

This is problematic if the encoder is used for a GUI application. For example, scrolling a menu requires a 2 detent rotation (instead of 1 detent). To the user this feels like the input is has missed a detent and is thus non-responsive.

A solution is to add an optional parameter, half_step, which causes the library to signal a rotation increment/decrement after seeing only 2 encoder state transitions.

This has been implemented in the following branch of the forked project.
https://github.com/urbite/micropython_rotary_encoder/tree/feature/half-step

**Comment by TTitanUA** [comment]
Pull request accepted. Commit: [Add half-step rotation increment/decrement parameter](https://github.com/TTitanUA/micropython_rotary_encoder/commit/20e7e9ed7925528e809980317e56a4f75cef0407)
